version: "3.7"

volumes:
  postgres_data: { }
  storage_data: { }
#  static :

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  chatsupport:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate_schemas --shared"
#              python manage.py runserver 0.0.0.0:8000"

    volumes:
      - storage_data:/chatsupport/media
#      - static:/static
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.dev
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_PORT=5432
    expose:
      - 8000
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis

#  nginx:
#    build: ./nginx
#    volumes:
#      - static:/static
#    ports:
#      - "80:80"
#    depends_on:
#      - chatsupport

  channels:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 chatsupport.asgi:channel_layers
    env_file:
      - .env.dev
    volumes:
      - .:/chatsupport
    ports:
      - "8001:8001"
    links:
      - redis